# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'stevendev/pipelines-flask-docker'
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhubconnection'
        repository: $(imageName)
        command: 'push'


- stage: Deploy
  displayName: Deploy image to Kubernetes
  jobs:
  - deployment: Deploy
    dependsOn:
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'flaskenvironment'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/app/manifests'
              Contents: '*.yml'
              TargetFolder: 'sss'

          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'flaskenvironment-Flaskdemocluster-default-1586793974934'
              manifests: '$(Build.ArtifactStagingDirectory)/manifests/*'

