apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "flaskdemocluster"
  labels: 
    app: "flaskdemocluster"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: "flaskdemocluster"
  template:
    metadata:
      labels:
        app: "flaskdemocluster"
    spec:
      containers:
        - name: "flaskdemoclustercont"
          image: "stevendev/pipelines-flask-docker"
          ports:
          - containerPort: 80
