apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "flaskdemocluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "flaskdemocluster"
    spec:
      containers:
        - name: "flaskdemocluster"
          image: "testcontainerregmonday.azurecr.io/flaskdemocluster"
          ports:
          - containerPort: 80