on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n Testcontainerregmonday -g Testcontainerregmonday920e-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n Testcontainerregmonday --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n Testcontainerregmonday --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n Testcontainerregmonday --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: testcontainerregmonday.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t testcontainerregmonday.azurecr.io/flaskdemocluster:${{ github.sha }}
        docker push testcontainerregmonday.azurecr.io/flaskdemocluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_flaskdemocluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep flaskdemocluster8220 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace flaskdemocluster8220`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: flaskdemocluster8220
        container-registry-url: testcontainerregmonday.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: flaskdemocludockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: flaskdemocluster8220
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          testcontainerregmonday.azurecr.io/flaskdemocluster:${{ github.sha }}
        imagepullsecrets: |
          flaskdemocludockerauth